### ISSUE TITLE
Path mouseover not accurate

### ISSUE THREAD

**Issue by jacquesh** [jacquesh/VisualizAncients#12]
The area that you can mouseover to highlight a player's path does not accurately match the path itself, it appears to be more along the lines of the convex hull of the path rather than the actual path. This is very confusing because it makes some paths very hard to highlight at certain points.

For example test2's path data starting at 10:34, naga's path middle makes a loop but if you put your mouse in the middle of the look it still highlights her path.

**Comment by AceFire6** [comment]
There is no easy way to solve this problem. This is the default functionality given by JCanvas as I assume there is no easy way to do it accurately for any number of points.
