### ISSUE TITLE
Inventory doesn't update while moused over

### ISSUE THREAD

**Issue by jacquesh** [jacquesh/VisualizAncients#20]
If an item gets used while you're moused over a hero, the shown inventory doesn't update, you have to move the mouse away and re-mouseover

**Comment by AceFire6** [comment]
Should this be done or can we assume if people are tracking a hero it'll be done by clicking?

**Comment by jacquesh** [comment]
I think theres a reasonable use-case for needing items to update for heroes you're just mousing over (for example people might stand still for a couple seconds if they're warding, in which case its easy to stay moused-over without selecting them). However for the purposes of getting the information, since you do actually have the option of selecting them anyways, I think its fine if we just leave it requiring you to select them (if only in the interest of getting this done).
