### ISSUE TITLE
Persistent hero selection

### ISSUE THREAD

**Issue by jacquesh** [jacquesh/VisualizAncients#21]
It would be really nice to be able to keep a hero selected without needing to stay moused over them (e.g by clicking on them or something). This relies on #20 being completed though.

**Comment by AceFire6** [comment]
I assume you want hover and then to be able to lock in the focus on a specific hero by clicking them?

**Comment by jacquesh** [comment]
Something to that effect ye, just so that if you want to see what a specific hero is doing you don't have to some how follow their hero around with your cursor.
