### ISSUE TITLE
Map Control readout

### ISSUE THREAD

**Issue by Voodoodrood** [jacquesh/VisualizAncients#29]
Would be good to have a gap between the blocks showing dire and radiant map control, also offsetting the percentage labels in these blocks vertically from one another would help.

**Comment by AceFire6** [comment]
This is what it looks like at the moment:
![c2a888d684 1](https://cloud.githubusercontent.com/assets/4126778/14091307/ce774616-f53f-11e5-81ed-cf4625aef1f8.jpg)

Are the map control changes sufficient?

**Comment by Voodoodrood** [comment]
Much better than it was, still think it would be nice to have the percent labels offset from each other but if that's a mission don't worry about it.
