### ISSUE TITLE
Background Map

### ISSUE THREAD

**Issue by Voodoodrood** [jacquesh/VisualizAncients#30]
Need to update the background map to the simplified version.

**Comment by AceFire6** [comment]
These are the options we have for backgrounds:

1. Normal minimap
![](http://puu.sh/nYf7A/7125057924.jpg)

2. Darkened minimap
![](http://puu.sh/nYeQw/3eb09e2545.jpg)

3. Simplified minimap
![](http://puu.sh/nYfbz/00fb1762fb.jpg)

3. Lightened Simplified minimap
![](http://puu.sh/nYfgJ/3fe4d35f1c.jpg)
